# Generated by Django 3.2.6 on 2025-03-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.URLField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
